CREATE TABLE CAMINHAO(
	ID_CAMINHAO SERIAL primary key,
	PLACA VARCHAR(20) unique not null,
	MARCA VARCHAR(20) not null,
	MODELO VARCHAR(20) not null,
	ANO VARCHAR(5) not null,
	KILOMETRAGEM NUMERIC not null,
	ULTIMA_ATUALIZACAO TIMESTAMP
);

CREATE TABLE CUSTOS(
	ID_CUSTO SERIAL primary key,
	ID_CAMINHAO INTEGER not null,
	DESCRICAO TEXT not null,
	VALOR NUMERIC not null,
	DATA_CUSTO DATE not null,
	CONSTRAINT fk_custos_caminhao FOREIGN KEY (ID_CAMINHAO) REFERENCES CAMINHAO (ID_CAMINHAO)
);

CREATE TABLE MOTORISTA(
	ID_MOTORISTA SERIAL primary key,
	ID_CAMINHAO INTEGER not null,
	NOME VARCHAR(50) not null,
	MEDIA_CONSUMO NUMERIC not null,
	CONSTRAINT fk_motorista_caminhao FOREIGN KEY (ID_CAMINHAO) REFERENCES CAMINHAO (ID_CAMINHAO)
);

